### ISSUE TITLE
XML Export file not generating on submission

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#120]
Issue:
------------
Credit app is submitted but no xml file shows up on the creditApp folder. The error message appearing in Eclipse shows:

> 16:08:52,520 WARN  [http-bio-8080-exec-25][RateFactorRulePersistenceImpl:2852] No RateFactorRule exists with the primary key 0
16:08:52,526 ERROR [PaymentCalculatorUtil:209] com.tamarack.creekridge.NoSuchRateFactorRuleException: No RateFactorRule exists with the primary key 0
16:08:52,578 ERROR [PaymentCalculatorUtil:264] java.lang.RuntimeException: java.lang.NullPointerException

When looking at the submitted creditAppID, the rateFactorRuleID appears to be 0 and it is preventing the xml file feature from working correctly.

Expected:
--------------
The rateFactorRuleID should be the rateFactorRuleID from the pricing option chosen to be used for the creditApp, not zero.

**Comment by tbstevens** [comment]
@divinami - reassigning to Oleg. Just noticed that the creditApp record is not saving the rateFactorRuleID.

**Comment by tbstevens** [comment]
@olegForce - retested. Similar error that occured with Manage Documents button. I emailed the error.

**Comment by OlegForce** [comment]
fixed?

**Comment by tbstevens** [comment]
@divinami - Mike I believe you're working on finishing this one up. Just wanted to be sure this issue remained open until resolved.

**Comment by divinami** [comment]
Fixed.

**Comment by Creekridge** [comment]
We haven't been shown any part of this functionality - not sure where to look for xml file - cannot test.

**Comment by tbstevens** [comment]
@Creekridge - The XML files will be exported to the CRCVIP server at the following location:
C:\portal\liferay-portal-6.2-ce-ga2\creditApps

Each file in the folder is an xml file titled "creditApp_[Customer Name]_[MMDDYYYY]_[HHMM].xml

**Comment by Creekridge** [comment]
The file generated, but there isn't any data in the file.

**Comment by tbstevens** [comment]
@Creekridge - I'm seeing a file in the folder path titled "creditApp_Test_01192015_1600" and there is data in the file.

><?xml version="1.0" encoding="UTF-8"?><CreditApp><model><model-name>com.tamarack.creekridge.model.CreditApp</model-name><column><column-name>creditAppId</column-name><column-value><![CDATA[1203]]></column-value></column><column><column-name>companyId</column-name><column-value><![CDATA[10157]]></column-value></column><column><column-name>userId</column-name><column-value><![CDATA[11120]]></column-value></column><column><column-name>userName</column-name><column-value><![CDATA[salesreptester]]></column-value></column><column><column-name>createDate</column-name><column-value><![CDATA[Tue Jan 13 10:34:37 CST 2015]]></column-value></column><column><column-name>modifiedDate</column-name><column-value><![CDATA[Mon Jan 19 16:00:41 CST 2015]]></column-value></column><column><column-name>groupId</column-name><column-value><![CDATA[14278]]></column-value></column><column><column-name>vendorId</column-name><column-value><![CDATA[14278]]></column-value></column><column><column-name>creditAppStatusId</column-name><column-value><![CDATA[3]]></column-value></column><column><column-name>productId</column-name><column-value><![CDATA[502]]></column-value></column><column><column-name>termId</column-name><column-value><![CDATA[103]]></column-value></column><column><column-name>purchaseOptionId</column-name><column-value><![CDATA[101]]></column-value></column><column><column-name>rateFactorRuleId</column-name><column-value><![CDATA[8]]></column-value></column><column><column-name>paymentAmount</column-name><column-value><![CDATA[4186.83]]></column-value></column><column><column-name>equipmentPrice</column-name><column-value><![CDATA[200000.0]]></column-value></column><column><column-name>equipmentDesc</column-name><column-value><![CDATA[Test]]></column-value></column><column><column-name>equipmentLocAsCustomerFlag</column-name><column-value><![CDATA[true]]></column-value></column><column><column-name>equipmentAddress1</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>equipmentAddress2</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>equipmentCity</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>equipmentState</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>equipmentZip</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>CustomerName</column-name><column-value><![CDATA[Test]]></column-value></column><column><column-name>CustomerDBAName</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>CustomerAddress1</column-name><column-value><![CDATA[111 Main Street]]></column-value></column><column><column-name>CustomerAddress2</column-name><column-value><![CDATA[111 Main Street]]></column-value></column><column><column-name>CustomerCity</column-name><column-value><![CDATA[Edina]]></column-value></column><column><column-name>CustomerState</column-name><column-value><![CDATA[MN]]></column-value></column><column><column-name>CustomerZip</column-name><column-value><![CDATA[55439]]></column-value></column><column><column-name>CustomerContact</column-name><column-value><![CDATA[John Smith]]></column-value></column><column><column-name>CustomerContactPhone</column-name><column-value><![CDATA[(555) 555-5555]]></column-value></column><column><column-name>CustomerContactFax</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>CustomerContactEmail</column-name><column-value><![CDATA[jsmith@test.com]]></column-value></column><column><column-name>CustomerBusinessDesc</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>CustomerBusinessType</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>CustomerBusinessStartDate</column-name><column-value><![CDATA[Tue Jan 13 00:00:00 CST 2015]]></column-value></column><column><column-name>CustomerBusinessIncorporatedState</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>CustomerBusinessFederalTaxID</column-name><column-value><![CDATA[]]></column-value></column></model><CreditAppPrincipals></CreditAppPrincipals><CreditAppBankReferences></CreditAppBankReferences><PurchaseOption><model><model-name>com.tamarack.creekridge.model.PurchaseOption</model-name><column><column-name>purchaseOptionId</column-name><column-value><![CDATA[101]]></column-value></column><column><column-name>companyId</column-name><column-value><![CDATA[10157]]></column-value></column><column><column-name>userId</column-name><column-value><![CDATA[10201]]></column-value></column><column><column-name>userName</column-name><column-value><![CDATA[test]]></column-value></column><column><column-name>createDate</column-name><column-value><![CDATA[Wed Nov 19 11:35:38 CST 2014]]></column-value></column><column><column-name>modifiedDate</column-name><column-value><![CDATA[Wed Nov 19 11:35:38 CST 2014]]></column-value></column><column><column-name>purchaseOptionName</column-name><column-value><![CDATA[FMV]]></column-value></column><column><column-name>sequenceNumber</column-name><column-value><![CDATA[1]]></column-value></column></model></PurchaseOption><Term><model><model-name>com.tamarack.creekridge.model.Term</model-name><column><column-name>termId</column-name><column-value><![CDATA[103]]></column-value></column><column><column-name>companyId</column-name><column-value><![CDATA[10157]]></column-value></column><column><column-name>userId</column-name><column-value><![CDATA[0]]></column-value></column><column><column-name>userName</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>createDate</column-name><column-value><![CDATA[null]]></column-value></column><column><column-name>modifiedDate</column-name><column-value><![CDATA[null]]></column-value></column><column><column-name>termMonths</column-name><column-value><![CDATA[48]]></column-value></column><column><column-name>termName</column-name><column-value><![CDATA[48 mo]]></column-value></column><column><column-name>sequenceNumber</column-name><column-value><![CDATA[0]]></column-value></column></model></Term><Product><model><model-name>com.tamarack.creekridge.model.Product</model-name><column><column-name>productId</column-name><column-value><![CDATA[502]]></column-value></column><column><column-name>companyId</column-name><column-value><![CDATA[10157]]></column-value></column><column><column-name>userId</column-name><column-value><![CDATA[0]]></column-value></column><column><column-name>userName</column-name><column-value><![CDATA[]]></column-value></column><column><column-name>createDate</column-name><column-value><![CDATA[null]]></column-value></column><column><column-name>modifiedDate</column-name><column-value><![CDATA[null]]></column-value></column><column><column-name>productName</column-name><column-value><![CDATA[0% for 6 months]]></column-value></column><column><column-name>sequenceNumber</column-name><column-value><![CDATA[2]]></column-value></column></model></Product><RateFactorRule><model><model-name>com.tamarack.creekridge.model.RateFactorRule</model-name><column><column-name>rateFactorRuleId</column-name><column-value><![CDATA[8]]></column-value></column><column><column-name>companyId</column-name><column-value><![CDATA[10157]]></column-value></column><column><column-name>userId</column-name><column-value><![CDATA[10201]]></column-value></column><column><column-name>userName</column-name><column-value><![CDATA[test]]></column-value></column><column><column-name>createDate</column-name><column-value><![CDATA[Wed Nov 19 11:35:38 CST 2014]]></column-value></column><column><column-name>modifiedDate</column-name><column-value><![CDATA[Wed Nov 19 11:35:38 CST 2014]]></column-value></column><column><column-name>productId</column-name><column-value><![CDATA[502]]></column-value></column><column><column-name>termId</column-name><column-value><![CDATA[103]]></column-value></column><column><column-name>purchaseOptionId</column-name><column-value><![CDATA[101]]></column-value></column><column><column-name>vendorId</column-name><column-value><![CDATA[14278]]></column-value></column><column><column-name>minPrice</column-name><column-value><![CDATA[0.0]]></column-value></column><column><column-name>rateFactor</column-name><column-value><![CDATA[0.006]]></column-value></column><column><column-name>effectiveDate</column-name><column-value><![CDATA[Wed Jan 01 00:00:00 CST 2014]]></column-value></column><column><column-name>active</column-name><column-value><![CDATA[true]]></column-value></column><column><column-name>expirationDate</column-name><column-value><![CDATA[Fri Jan 01 00:00:00 CST 2016]]></column-value></column></model></RateFactorRule><Vendor><model><model-name>com.liferay.portal.model.Group</model-name><column><column-name>VendorName</column-name><column-value><![CDATA[Vendor1]]></column-value></column><column><column-name>VendorAddress</column-name><column-value><![CDATA[null null]]></column-value></column><column><column-name>Vendor Cit</column-name><column-value><![CDATA[null]]></column-value></column><column><column-name>VendorState</column-name><column-value><![CDATA[null]]></column-value></column><column><column-name>VendorZip</column-name><column-value><![CDATA[</Vendor></CreditApp>

**Comment by Creekridge** [comment]
Okay – there is data, but it’s not a valid xml format.  Valid xml format would be <CreditAppID>10157</CreditAppID> for each field.

**Comment by kdolan12** [comment]
@Creekridge Sandy - This is valid XML.  The reason why the XML is formatted in this fashion is that Java has some native XML outputs that it can perform with not much programmatic effort.  Since your end goal was to apply a style sheet to the XML anyways, we did not think there is much ROI in trying to make this formatted in a pretty way.  

I have created a sample XSL that will convert the Java generated XML into something more like the XML format you were looking for in the above thread.  You can enhance this XSL to get it to the Rapport format as needed.

GIT HUB does not support me attaching XML files, so I'll email you the XML Input, the XSL, and the XML Output for your review.  Let me know if you have additional concerns.

**Comment by Creekridge** [comment]
Confirmed it's working and the file is translatable as demonstrated by the e-mailed files.  Will need to further discuss how to update that transform to map into Rapport using current Import process (IDS Import tool) that Tamarack assisted us with.  Can close issue and that would be out of scope for this project.
